### ISSUE TITLE
No commits link

### ISSUE THREAD

**Issue by medievil1** [Kir-Antipov/GitHub-Defreshed#10] opened 2020-07-13 21:24 UTC
comes up as null null
Screenshot below as example 
![image](https://user-images.githubusercontent.com/38597905/87355036-a45d4e80-c52d-11ea-8bcb-5922595a3f4b.png)

***EDIT***
I should add that is WITH the new "enhancement" 
with it disabled it looks normal with commits in the old spot just like it always was 
![image](https://user-images.githubusercontent.com/38597905/87355682-c60b0580-c52e-11ea-82c9-0b2ab304139d.png)

**Comment by Kir-Antipov** [comment] 2020-07-14 02:23
Yeah, I know. As I said [here](https://github.community/t/how-to-opt-out-of-the-new-ui/119416/181?u=kir-antipov), this issue is caused by the new "Latest commit design update"-feature. But it's still optional and didn't leave preview stage, so master-branch doesn't support, cause master-branch targets the <ins>actual</ins> GitHub state. 

Take a look at #7, I've already prepared the script to this update, so `latest-commit-design-update-branch` just waits to be merged with master, and I'll do it when update will be finally released. 

Until that happens, you have 2 options:
 - You can simply disable this optional preview
 - Or you can build `latest-commit-design-update` and use it. But I don’t see any sense in this, since the page will still look the same as if you just clicked the **Disable** button on the **Feature preview** menu.

**Comment by Kir-Antipov** [comment] 2020-07-14 02:25
Don’t worry, I always keep the script up to date, so the script will always keep the GitHub interface "in touch" :)

**Comment by Kir-Antipov** [comment] 2020-07-14 02:27
I'll leave this issue (as well as #7) open until the update to make sure that everything is ok

**Comment by medievil1** [comment] 2020-07-14 03:40
gotcha, didn't realize it was the same issue... I do wonder one thing, release count is 0 but I know cxbx-reloaded has several when you click releases..not a big deal, but it might throw some off thinking there is no release...could be their "Pre-release" listing throwing it off I suppose

**Comment by Kir-Antipov** [comment] 2020-07-14 09:47
@medievil1, yep, as you can see here:

![image](https://user-images.githubusercontent.com/40232067/87410576-2c476500-c5cf-11ea-87f8-885d7e9d9caf.png)

GitHub doesn't treat pre-releases as releases, so original interface wouldn't show them either. In case you propose to display the number of tags as the number of releases: tags are more general thing, 'cause every release is a tag, but not every tag is release.

**Closed** 2020-07-22 10:16 UTC
Labels: duplicate
